const env = {
  ajaxpipe_token: null,
  compat_iframe_token: null,
  iframeKey: '',
  iframeTarget: '',
  iframeToken: '',
  isCQuick: !1,
  jssp_header_sent: !1,
  jssp_targeting_enabled: !1,
  loadHyperion: !1,
  start: Date.now(),
  nocatch: !1,
  useTrustedTypes: !1,
  isTrustedTypesReportOnly: !1,
  enableDefaultTrustedTypesPolicy: !1,
  ig_server_override: '',
  barcelona_server_override: '',
  ig_mqtt_wss_endpoint: '',
  ig_mqtt_polling_endpoint: '',
  ajaxpipe_token: null,
  compat_iframe_token: null,
  iframeKey: '',
  iframeTarget: '',
  iframeToken: '',
  isCQuick: false,
  jssp_header_sent: false,
  jssp_targeting_enabled: false,
  loadHyperion: false,
  start: Date.now(),
  nocatch: false,
  useTrustedTypes: false,
  isTrustedTypesReportOnly: false,
  enableDefaultTrustedTypesPolicy: false,
  ig_server_override: '',
  barcelona_server_override: '',
  ig_mqtt_wss_endpoint: '',
  ig_mqtt_polling_endpoint: '',
  routing_namespace: 'fb_comet',
  ghlss: 'c1pLRK',
  use_fbt_virtual_modules: true,
  gk_clear_js_factory_after_used: true,
  brsid: '7398731302898342186',
};

window.Env && Object.assign(env, window.Env);
window.Env = env;

export { env };
